#
# This source file is part of the Intake based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      security-events: write
      actions: read
  iosapptestflightdeployment:
    name: iOS App TestFlight Deployment
    needs: buildandtest
    uses: CS342/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    secrets: inherit
    with:
      googleserviceinfoplistpath: 'Intake/Supporting Files/GoogleService-Info.plist'
      setupsigning: true
      fastlanelane: beta
